/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import { Contract, ContractTransaction } from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface EventsInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "BaseInitialized(string,string,uint256)": EventFragment;
    "CollectModuleWhitelisted(address,bool,uint256)": EventFragment;
    "CollectNFTDeployed(uint256,uint256,address,uint256)": EventFragment;
    "CollectNFTInitialized(uint256,uint256,uint256)": EventFragment;
    "CollectNFTTransferred(uint256,uint256,uint256,address,address,uint256)": EventFragment;
    "Collected(address,uint256,uint256,uint256,uint256,bytes,uint256)": EventFragment;
    "CommentCreated(uint256,uint256,string,uint256,uint256,bytes,address,bytes,address,bytes,uint256)": EventFragment;
    "DefaultProfileSet(address,uint256,uint256)": EventFragment;
    "DispatcherSet(uint256,address,uint256)": EventFragment;
    "EmergencyAdminSet(address,address,address,uint256)": EventFragment;
    "FeeModuleBaseConstructed(address,uint256)": EventFragment;
    "FollowModuleSet(uint256,address,bytes,uint256)": EventFragment;
    "FollowModuleWhitelisted(address,bool,uint256)": EventFragment;
    "FollowNFTDelegatedPowerChanged(address,uint256,uint256)": EventFragment;
    "FollowNFTDeployed(uint256,address,uint256)": EventFragment;
    "FollowNFTInitialized(uint256,uint256)": EventFragment;
    "FollowNFTTransferred(uint256,uint256,address,address,uint256)": EventFragment;
    "FollowNFTURISet(uint256,string,uint256)": EventFragment;
    "Followed(address,uint256[],bytes[],uint256)": EventFragment;
    "FollowsApproved(address,uint256,address[],bool[],uint256)": EventFragment;
    "FollowsToggled(address,uint256[],bool[],uint256)": EventFragment;
    "GovernanceSet(address,address,address,uint256)": EventFragment;
    "MirrorCreated(uint256,uint256,uint256,uint256,bytes,address,bytes,uint256)": EventFragment;
    "ModuleBaseConstructed(address,uint256)": EventFragment;
    "ModuleGlobalsCurrencyWhitelisted(address,bool,bool,uint256)": EventFragment;
    "ModuleGlobalsGovernanceSet(address,address,uint256)": EventFragment;
    "ModuleGlobalsTreasuryFeeSet(uint16,uint16,uint256)": EventFragment;
    "ModuleGlobalsTreasurySet(address,address,uint256)": EventFragment;
    "PostCreated(uint256,uint256,string,address,bytes,address,bytes,uint256)": EventFragment;
    "ProfileCreated(uint256,address,address,string,string,address,bytes,string,uint256)": EventFragment;
    "ProfileCreatorWhitelisted(address,bool,uint256)": EventFragment;
    "ProfileImageURISet(uint256,string,uint256)": EventFragment;
    "ProfileMetadataSet(uint256,string,uint256)": EventFragment;
    "ReferenceModuleWhitelisted(address,bool,uint256)": EventFragment;
    "StateSet(address,uint8,uint8,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BaseInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectModuleWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectNFTDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectNFTInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectNFTTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Collected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CommentCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DefaultProfileSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DispatcherSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyAdminSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeModuleBaseConstructed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowModuleSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowModuleWhitelisted"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "FollowNFTDelegatedPowerChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowNFTDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowNFTInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowNFTTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowNFTURISet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Followed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowsApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FollowsToggled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MirrorCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ModuleBaseConstructed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ModuleGlobalsCurrencyWhitelisted"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ModuleGlobalsGovernanceSet"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ModuleGlobalsTreasuryFeeSet"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ModuleGlobalsTreasurySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PostCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProfileCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProfileCreatorWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProfileImageURISet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProfileMetadataSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReferenceModuleWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StateSet"): EventFragment;
}

export class Events extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: EventsInterface;

  functions: {};

  callStatic: {};

  filters: {
    BaseInitialized(name: null, symbol: null, timestamp: null): EventFilter;

    CollectModuleWhitelisted(
      collectModule: string | null,
      whitelisted: boolean | null,
      timestamp: null
    ): EventFilter;

    CollectNFTDeployed(
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      collectNFT: string | null,
      timestamp: null
    ): EventFilter;

    CollectNFTInitialized(
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      timestamp: null
    ): EventFilter;

    CollectNFTTransferred(
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      collectNFTId: BigNumberish | null,
      from: null,
      to: null,
      timestamp: null
    ): EventFilter;

    Collected(
      collector: string | null,
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      rootProfileId: null,
      rootPubId: null,
      collectModuleData: null,
      timestamp: null
    ): EventFilter;

    CommentCreated(
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      contentURI: null,
      profileIdPointed: null,
      pubIdPointed: null,
      referenceModuleData: null,
      collectModule: null,
      collectModuleReturnData: null,
      referenceModule: null,
      referenceModuleReturnData: null,
      timestamp: null
    ): EventFilter;

    DefaultProfileSet(
      wallet: string | null,
      profileId: BigNumberish | null,
      timestamp: null
    ): EventFilter;

    DispatcherSet(
      profileId: BigNumberish | null,
      dispatcher: string | null,
      timestamp: null
    ): EventFilter;

    EmergencyAdminSet(
      caller: string | null,
      oldEmergencyAdmin: string | null,
      newEmergencyAdmin: string | null,
      timestamp: null
    ): EventFilter;

    FeeModuleBaseConstructed(
      moduleGlobals: string | null,
      timestamp: null
    ): EventFilter;

    FollowModuleSet(
      profileId: BigNumberish | null,
      followModule: null,
      followModuleReturnData: null,
      timestamp: null
    ): EventFilter;

    FollowModuleWhitelisted(
      followModule: string | null,
      whitelisted: boolean | null,
      timestamp: null
    ): EventFilter;

    FollowNFTDelegatedPowerChanged(
      delegate: string | null,
      newPower: BigNumberish | null,
      timestamp: null
    ): EventFilter;

    FollowNFTDeployed(
      profileId: BigNumberish | null,
      followNFT: string | null,
      timestamp: null
    ): EventFilter;

    FollowNFTInitialized(
      profileId: BigNumberish | null,
      timestamp: null
    ): EventFilter;

    FollowNFTTransferred(
      profileId: BigNumberish | null,
      followNFTId: BigNumberish | null,
      from: null,
      to: null,
      timestamp: null
    ): EventFilter;

    FollowNFTURISet(
      profileId: BigNumberish | null,
      followNFTURI: null,
      timestamp: null
    ): EventFilter;

    Followed(
      follower: string | null,
      profileIds: null,
      followModuleDatas: null,
      timestamp: null
    ): EventFilter;

    FollowsApproved(
      owner: string | null,
      profileId: BigNumberish | null,
      addresses: null,
      approved: null,
      timestamp: null
    ): EventFilter;

    FollowsToggled(
      owner: string | null,
      profileIds: null,
      enabled: null,
      timestamp: null
    ): EventFilter;

    GovernanceSet(
      caller: string | null,
      prevGovernance: string | null,
      newGovernance: string | null,
      timestamp: null
    ): EventFilter;

    MirrorCreated(
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      profileIdPointed: null,
      pubIdPointed: null,
      referenceModuleData: null,
      referenceModule: null,
      referenceModuleReturnData: null,
      timestamp: null
    ): EventFilter;

    ModuleBaseConstructed(hub: string | null, timestamp: null): EventFilter;

    ModuleGlobalsCurrencyWhitelisted(
      currency: string | null,
      prevWhitelisted: boolean | null,
      whitelisted: boolean | null,
      timestamp: null
    ): EventFilter;

    ModuleGlobalsGovernanceSet(
      prevGovernance: string | null,
      newGovernance: string | null,
      timestamp: null
    ): EventFilter;

    ModuleGlobalsTreasuryFeeSet(
      prevTreasuryFee: BigNumberish | null,
      newTreasuryFee: BigNumberish | null,
      timestamp: null
    ): EventFilter;

    ModuleGlobalsTreasurySet(
      prevTreasury: string | null,
      newTreasury: string | null,
      timestamp: null
    ): EventFilter;

    PostCreated(
      profileId: BigNumberish | null,
      pubId: BigNumberish | null,
      contentURI: null,
      collectModule: null,
      collectModuleReturnData: null,
      referenceModule: null,
      referenceModuleReturnData: null,
      timestamp: null
    ): EventFilter;

    ProfileCreated(
      profileId: BigNumberish | null,
      creator: string | null,
      to: string | null,
      handle: null,
      imageURI: null,
      followModule: null,
      followModuleReturnData: null,
      followNFTURI: null,
      timestamp: null
    ): EventFilter;

    ProfileCreatorWhitelisted(
      profileCreator: string | null,
      whitelisted: boolean | null,
      timestamp: null
    ): EventFilter;

    ProfileImageURISet(
      profileId: BigNumberish | null,
      imageURI: null,
      timestamp: null
    ): EventFilter;

    ProfileMetadataSet(
      profileId: BigNumberish | null,
      metadata: null,
      timestamp: null
    ): EventFilter;

    ReferenceModuleWhitelisted(
      referenceModule: string | null,
      whitelisted: boolean | null,
      timestamp: null
    ): EventFilter;

    StateSet(
      caller: string | null,
      prevState: BigNumberish | null,
      newState: BigNumberish | null,
      timestamp: null
    ): EventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
