/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISAIReportRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getSAIReport(address,address)": FunctionFragment;
    "registerNewSAIReport(address,address,uint8,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSAIReport",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNewSAIReport",
    values: [string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSAIReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNewSAIReport",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISAIReportRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISAIReportRegistryInterface;

  functions: {
    getSAIReport(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, number, string] & {
          organization: string;
          auditor: string;
          targetGoalInSDGs: number;
          contentHashOfSAIReport: string;
        }
      ] & {
        _saiReport: [string, string, number, string] & {
          organization: string;
          auditor: string;
          targetGoalInSDGs: number;
          contentHashOfSAIReport: string;
        };
      }
    >;

    "getSAIReport(address,address)"(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, number, string] & {
          organization: string;
          auditor: string;
          targetGoalInSDGs: number;
          contentHashOfSAIReport: string;
        }
      ] & {
        _saiReport: [string, string, number, string] & {
          organization: string;
          auditor: string;
          targetGoalInSDGs: number;
          contentHashOfSAIReport: string;
        };
      }
    >;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerNewSAIReport(address,address,uint8,string)"(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getSAIReport(
    organization: string,
    auditor: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, string] & {
      organization: string;
      auditor: string;
      targetGoalInSDGs: number;
      contentHashOfSAIReport: string;
    }
  >;

  "getSAIReport(address,address)"(
    organization: string,
    auditor: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, string] & {
      organization: string;
      auditor: string;
      targetGoalInSDGs: number;
      contentHashOfSAIReport: string;
    }
  >;

  registerNewSAIReport(
    organization: string,
    auditor: string,
    _targetGoalInSDGs: BigNumberish,
    contentHashOfSAIReport: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerNewSAIReport(address,address,uint8,string)"(
    organization: string,
    auditor: string,
    _targetGoalInSDGs: BigNumberish,
    contentHashOfSAIReport: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getSAIReport(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, string] & {
        organization: string;
        auditor: string;
        targetGoalInSDGs: number;
        contentHashOfSAIReport: string;
      }
    >;

    "getSAIReport(address,address)"(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, string] & {
        organization: string;
        auditor: string;
        targetGoalInSDGs: number;
        contentHashOfSAIReport: string;
      }
    >;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerNewSAIReport(address,address,uint8,string)"(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getSAIReport(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSAIReport(address,address)"(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerNewSAIReport(address,address,uint8,string)"(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSAIReport(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSAIReport(address,address)"(
      organization: string,
      auditor: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerNewSAIReport(address,address,uint8,string)"(
      organization: string,
      auditor: string,
      _targetGoalInSDGs: BigNumberish,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
