/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISAIReportRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getSAIReport(address)": FunctionFragment;
    "registerNewSAIReport(address,address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSAIReport",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNewSAIReport",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSAIReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNewSAIReport",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISAIReportRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISAIReportRegistryInterface;

  functions: {
    getSAIReport(
      organization: string,
      overrides?: CallOverrides
    ): Promise<[string] & { _contentHashOfSAIReport: string }>;

    "getSAIReport(address)"(
      organization: string,
      overrides?: CallOverrides
    ): Promise<[string] & { _contentHashOfSAIReport: string }>;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerNewSAIReport(address,address,string)"(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getSAIReport(
    organization: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getSAIReport(address)"(
    organization: string,
    overrides?: CallOverrides
  ): Promise<string>;

  registerNewSAIReport(
    organization: string,
    auditor: string,
    contentHashOfSAIReport: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerNewSAIReport(address,address,string)"(
    organization: string,
    auditor: string,
    contentHashOfSAIReport: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getSAIReport(
      organization: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSAIReport(address)"(
      organization: string,
      overrides?: CallOverrides
    ): Promise<string>;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerNewSAIReport(address,address,string)"(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getSAIReport(
      organization: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSAIReport(address)"(
      organization: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerNewSAIReport(address,address,string)"(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSAIReport(
      organization: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSAIReport(address)"(
      organization: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerNewSAIReport(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerNewSAIReport(address,address,string)"(
      organization: string,
      auditor: string,
      contentHashOfSAIReport: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
