/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISAIReportRegistry } from "../ISAIReportRegistry";

export class ISAIReportRegistry__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISAIReportRegistry {
    return new Contract(address, _abi, signerOrProvider) as ISAIReportRegistry;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "organization",
        type: "address",
      },
    ],
    name: "getSAIReport",
    outputs: [
      {
        internalType: "string",
        name: "_contentHashOfSAIReport",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "organization",
        type: "address",
      },
      {
        internalType: "address",
        name: "auditor",
        type: "address",
      },
      {
        internalType: "string",
        name: "contentHashOfSAIReport",
        type: "string",
      },
    ],
    name: "registerNewSAIReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
